### ISSUE TITLE
Update NGO activity domains

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#303]
Please update the list in ONGHub 
<img width="697" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/70c51ba0-a134-4f7b-963d-911834050d3c">

with this one:
List of activity domains
https://docs.google.com/spreadsheets/d/1cnk_c7nZg7KVtSlZ_TZT8RaB8tJtEMPKiMTgwCxCGEE/edit?usp=sharing

**Comment by anastk-code4** [comment]
Can we replace the current ui component (those chips) with a multiple select dropdown?

**Comment by radulescuandrew** [comment]
For statistical and filtering purposes, the domains are kept in the database. We can easily add them to the database (replacing the current ones) but not in multi-language. This requires additional work to implement internationalization on the backend to return data based on locale. 

To be discussed. 

@anastk-code4 @overeha

**Comment by birloiflorian** [comment]
For initial version we keep them in the database, we will just update the domain list.

**Comment by radulescuandrew** [comment]
Done, added to db. @overeha
