### ISSUE TITLE
[Login] When resetting one's password, email field does not have format validation

### ISSUE THREAD

**Issue by TerezaPirvan** [code4romania/onghub#317]
Test case description 
Check if "forgot you're  password" button works 

Steps to reproduce the behavior
1. From main page press on "Intra in cont" button (Upper right)                   
2. Click on the "Forgot your password" hyperlink (below the password field)
3. On the e-mail field write "123" 
4. Click on "Reset my password" 

Expected behavior
The email field should only accept the correct form of email

Actual behavior
The field accepts an invalid email form.

Device information
 - OS: Windows 10 
 - Browser Google Chrome
 - Version: 111.0.5563.147 

**Additional context**
![Screenshot forget password ](https://github.com/code4romania/onghub/assets/137605717/3bf3e66d-4592-4140-92c6-3c63c4bf30f4)

**Comment by radulescuandrew** [comment]
Cognito's hosted UI doesn't provide a direct way to add custom regular expressions (regex) for email validation, nor manual updates to the FE logic. 

A lambda trigger can be implemented to check but there is no benefit to that because of the lambda costs. 

Can't do.

**Comment by radulescuandrew** [comment]
@overeha I will close this based on our discussion.
