### ISSUE TITLE
[Account] Cannot edit email address and user's name

### ISSUE THREAD

**Issue by TerezaPirvan** [code4romania/onghub#318]
Describe the bug
Check if the account details can be changed

1. Sign in with e-mail (tudor.amariei+admin2@commitglobal.org) and password (heg1BUN0qgz1xkz_vjk )
2. Click on the name "Tudor Adoi" (upper right)
3. Select " Contul meu" from the drop-down list and click. 

Expected behavior
The presence of a button to be able to edit both the name and the email

Actual behavior 
There is no button to edit name or email.

Device information
 - OS: Windows 10 (OS build 19045.3324)
 - Browser: Google Chrome
 - Version: 22H2 

**Additional context**
![Screenshot account details](https://github.com/code4romania/onghub/assets/137605717/a559c4ce-90dc-4941-93c6-2f439a2618a7)

**Comment by AnaBlidaru** [comment]
Has been decided to keep it this way. Only super admins can change this
