### ISSUE TITLE
[Registration] A logged-in user can access the Registration form and complete it

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#320]
**Describe the bug**
A logged in user is able to access the Sign up form and complete it while being logged in. This can be confusing for the user.

**Steps to reproduce the behavior**
1. Login with an account
2. Go to https://app-staging.onghub.ro/new/account

**Expected behavior**
When accessing the sign-up page, the logged in user should be redirected to a page that says 'you're already logged in. want to log out and create a new account?'. 

**Screenshots**
<img width="1423" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/e76a014c-6ffd-427a-9860-58b75efac843"> 
<img width="1440" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/d237b5e8-a93b-4a52-9791-24073f54a579">

**Comment by birloiflorian** [comment]
As of now, if the user will try to access the registration route while logged in it will be redirected to home.
