### ISSUE TITLE
[NGO Profile] Overview: The NGO appears updated in the system and the recommended date for the next update is in the past.

### ISSUE THREAD

**Issue by TerezaPirvan** [code4romania/onghub#325]
Describe the bug
Although the NGO appears in the system as updated, it is recommended that the next update to be done in the past, not in the future.

Steps to reproduce the behavior
1. From the main page click on "ONG-uri" from the multi-select menu (on the left)
2. Click the"Filtre" button (upper right)
3. Click the „Status actualizare date” filter and select „Actualizat” from the drop-down list
4. Check the second NGO (Confederatia Nationala Rutiera) by clicking on the 3 dots on the right and selecting from the drop-down list  "Vizualizeaza ONG"
5. The recommendation for the next update is from the past ( 30.06.2023)

Expected behavior
If the NGO appears in the system as updated, the following dates for the update recommendation should appear in the future.

Actual behavior
The date when the next update is recommended is in past, although the NGO is olredy updated.

Device information
  - OS: Windows 10 (OS build 19045.3324)
 - Browser: Google Chrome
 - Version: 22H2 

**Additional context**
![Screenshot ONG update ](https://github.com/code4romania/onghub/assets/137605717/004fbfc6-d939-4873-b3ed-5faaebc9656f)

The same error occurs with the following NGOs:
- Ordinul Consilierilor Juridici Din România
- Asociația TEST REGISTER 22.05 modificat mobile
- Asociatia Zona Verde
- TestOng11

**Comment by AnaBlidaru** [comment]
fixed
