### ISSUE TITLE
[Dashboard] The total number  of users in the dashboard does not correspond to the total number of users within the NGOs. 

### ISSUE THREAD

**Issue by TerezaPirvan** [code4romania/onghub#326]
Describe the bug
The „Numărul total de utilizatori individuali” in the dashboard is 72, but counting each separately from each NGO, the number of users is only 50.

Precondition: 
Logged in with your email (tudor.amariei+admin2@commitglobal.org) and password (heg1BUN0qgz1xkz_vjk)

Steps to reproduce the behavior
1. The „Numărul total de utilizatori” in the dashboard is 72
2. Click on "ONG-uri" from the multi-select menu (on the left)
3. Counting the number of users from each NGO, there will be a total of 50. 
4. The numbers do not match.

Expected behavior
The total number of individual users in the dashboard should correspond to the current number of users from all organizations.

Actual behavior
The total number of individual users in the dashboard is different from the actual number of users in all organizations.

Device information
  - OS: Windows 10 (OS build 19045.3324)
 - Browser: Google Chrome
 - Version: 22H2 

**Additional context**
![Screenshot 72](https://github.com/code4romania/onghub/assets/137605717/c83e40af-cbcc-4e8f-96b9-0c5914c2ecb4)

**Comment by dragos1195** [comment]
Ca SuperAdmin, in Dashboard pe sectiunea de statistici contorizam pe "UserCount" toti utilizatorii (inclusiv Admini si SuperAdmini). 

Dar pe celelalte view-uri (Organization List in cazul de mai sus), expunem doar Employees.

Easy fix ar fi sa excludem count-ul adminilor si superadminilor din statistica (usercount).

Altfel, ar trebui sa includem adminii in fiecare statistica + views (tabele).

Ce decizie luam?
@anastk-code4 @overeha

**Comment by radulescuandrew** [comment]
@overeha please have a look.

**Comment by radulescuandrew** [comment]
@dragos1195 No action is needed. Keep it like this for the moment.
