### ISSUE TITLE
[Employees] Change the page AdminONG is redirected to, after sending an invite for a new employee user

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#331]
**Steps to reproduce the behavior**
1. Log in with an AdminONG account
2. Go to 'Utilizatori' (https://app-staging.onghub.ro/users/list)
3. Click on 'Add new' button (https://app-staging.onghub.ro/user)
4. Fill in user details and submit (click on 'Send invite' button)
5. User is redirected to https://app-staging.onghub.ro/users/list
 
**Expected behavior**
After clicking on 'Send invite' button, AdminONG user is redirected to https://app-staging.onghub.ro/users/invites .

**Comment by radulescuandrew** [comment]
Done.
