### ISSUE TITLE
[Employees] Invite employee to join ONGHub, link in email is broken

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#332]
**Steps to reproduce the behavior**
1. Log in with an AdminONG account
2. Go to 'Utilizatori' (https://app-staging.onghub.ro/users/list)
3. Click on 'Add new' button (https://app-staging.onghub.ro/user)
4. Fill in user details and submit (click on 'Send invite' button)

5. Go to check the email the invite was sent on
6. Open email, click on yellow button
7. New tab opens, but link is broken

**Expected behavior**
7. New tab opens, with ONGHub login screen.

**Screenshots**
<img width="1225" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/70a7e29a-d3e8-49ef-9277-142fc1f9b84e">

<img width="1423" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/3bc8f582-7543-4c94-ae15-bf48deb1a6a3">

**Comment by radulescuandrew** [comment]
Made a change, need to wait for `terraform apply` to test. 
The link will be changed with "Acceseaza ONGHub" and the user has to log in and change the temporary password. 

Keep you posted here :)
