### ISSUE TITLE
[Employee user] Add an extra step (modal) when user wants to delete their own account

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#334]
**Describe the bug**
When an Employee user wants to delete their account, they hit the "delete my account" button and the account is deleted immediately. This behavior is not good for error prevention. 

**Steps to reproduce the behavior**
1. Login as Employee user
2. Go to My account (Account settings)
3. Click on Delete account button

**Expected behavior**
User clicks on "delete my account" button.
User sees a modal asking whether they want to proceed in deleting their account, or go back. If they click to confirm they want to proceed, the account is deleted. 
User is redirected to a page saying their account was deleted successfully.

**Comment by radulescuandrew** [comment]
@anastk-code4 The modal is displayed. Where did you test it? Please provide a video if this is still the case, or close the issue. Thanks!

**Comment by radulescuandrew** [comment]
@overeha Please check
