### ISSUE TITLE
[NGO Profile] Subsections of the NGO Profile use the same translations

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#337]
**Describe the bug**
When editing the NGO profile, subtitles for different sections must be individually customizable.

Texts with issues:
- `common.information: "Aceste informații vor fi publice, atenție la ce împărtășești."`
  - appears in 28 places in 12 files
- `organization.description: "Administrează de aici profilul tău de organizație pentru a putea accesa aplicațiile disponibile."`
  - appears in 2 places (estimate, this was harder to find accurately)
- `organization.data_update: "Z8bR4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Unde apare asta? Te rugăm să actualizezi datele din această secțiune la un interval stabilit de timp."`
  - appears in 4 places in 2 files
- `part_of_helper: "De exemplu, lorem ipsum. Help text."`
  - appears for all the fields in `Organization activity` even though each section has its helper

**Steps to reproduce the behavior**
1. Go to `/organization/general` on an organization admin account
2. Click on 'Edit'
3. Scroll down to 'Date generale'
4. The subtitle is 'Aceste informatii vor fi publice, atentie la ce impartasesti.'
5. Scroll down to 'Persoana de contact in relatia cu ONGHub'
6. The subtitle is 'Lorem ipsum. Încarcă logo-ul organizației tale, la o calitate cât mai bună.'
7. Scroll down to 'Comunicare si social media', 'Strangere de fonduri'
8. The subtitle is 'Aceste informatii vor fi publice, atentie la ce impartasesti.'

**Expected behavior**
The subtitles of all subsections should be individually customizable. 
The subtitles should reference different text paths from the `translations.json` files, even if the texts are the same.

**Screenshots**

How it looks now (From `Figma > Design ONG Hub / Web Freeze`)
![Image showing the current texts for Fundraising](https://github.com/code4romania/onghub/assets/2820084/80ca8803-2ece-4173-b3d1-e63ebc83c766)
![Image showing the current texts for Communication social media](https://github.com/code4romania/onghub/assets/2820084/319c60e6-c25d-4180-b2d8-154f89f689db)

How it should look like (From `Figma > Design ONG Hub / Romanian`)
![Image showing the expected texts for Fundraising](https://github.com/code4romania/onghub/assets/2820084/2668d5eb-3b46-4d96-a207-b6889a10cf5b)
![Image showing the expected texts for Communication social media](https://github.com/code4romania/onghub/assets/2820084/c08b20f6-92aa-4b5a-8b31-8f0b3010b093)

**Additional context**
⚠️ When making changes, please take into account the changes from #336 
Please merge those changes beforehand, or if there are issues, contact me (@tudoramariei), @AnaBlidaru, or @anastk-code4.

**Comment by overeha** [comment]
can we get the new jsons to finish up the texts now that we can add these as well @tudoramariei is this something you can help with today pls?

**Comment by tudoramariei** [comment]
I made #415 now
I went through the Romanian locales and fixed what issues I could find easily and then ran an auto-translation to generate the English JSON
I also added some TODOs for some lone `Lorem Ipsum`-s I found

It would be great if someone could have a more in-depth look at the documents
