### ISSUE TITLE
[Login] When user inputs unmatchy email+pass, page refreshes and clears the email field

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#338]
**Describe the problem**
When user inputs unmatchy email+pass, page refreshes and clears the email field.

**Steps to reproduce the behavior**
1. Go to https://app-staging.onghub.ro/login 
2. Fill in unmatchy email+password
3. Click on login
4. See behavior

**Expected behavior**
When page refreshes, if the user filled in an email linked to an existing account, the field should be pre-filled with the email they previously inputted.

**Screenshots**
<img width="1436" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/2003bddc-99a3-4862-b9fd-59866a1d9a71">

**Comment by mirunaioana-msc** [comment]
This is a feature not a bug for security purposes.
