### ISSUE TITLE
[Registration] When an AdminONG account is approved by SuperAdmin, AdminONG receives 2 emails

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#346]
**Describe the bug**
When an AdminONG account is approved by SuperAdmin, AdminONG receives 2 emails:
email1: 
<img width="1078" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/41a04558-776e-43cc-925d-e3a4241a4ce0"> 
email2, with password setup: 
<img width="1078" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/1b4cfdc3-f874-47ed-9d33-c15514e28e6b">

This might be confusing for user.

**Steps to reproduce the behavior**
1. Go through registration form ( https://app-staging.onghub.ro/new/account ) to create an AdminONG request
2. Login as SuperAdmin in ONGHub, approve the new AdminONG request to join ONGHub
3. Check AdminONG email address to see the 2 new emails

**Expected behavior**
AdminONG only receives email2 (to set their password).

**Comment by radulescuandrew** [comment]
As requested and expected.  
1st email: Organization approved (sent by us)
2nd email: User created (sent by AWS Cognito)

**Comment by radulescuandrew** [comment]
Closed as per our discussion.
