### ISSUE TITLE
[NGO profile] The total income/expenditure of an organization isn't added

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#352]
**Describe the bug**
The `Total` field is not populated with the data from ANAF.

**Steps to reproduce the behavior**
1. Use a screen that allows for at least a 1650px wide window
2. Log in to an organization admin's account
3. Go to the `/organization/data` page
4. Open the `Financial info` tab
5. Edit one of the reports
6. Check the `Total Venituri` amount

**Expected behavior**
The value of the total should be the one extracted from the public ANAF endpoint
https://webservicesp.anaf.ro/bilant?an=<YEAR>&cui=<ORG_CUI>

**Screenshots**

![Screenshot 2023-09-29 at 11 40 24](https://github.com/code4romania/onghub/assets/2820084/e3ed876a-7fa4-4bc0-977a-d6e45c7e1a1b)
![Screenshot 2023-09-29 at 11 40 48](https://github.com/code4romania/onghub/assets/2820084/ade254b2-2951-421d-a894-794e82ae00f5)

**Device information**
 - OS: MacOS 13.5.2
 - Browser: Chrome 117.0.5938.92 [ARM]

**Additional context**
You can test with this URL: https://webservicesp.anaf.ro/bilant?an=2022&cui=36317167

**Comment by radulescuandrew** [comment]
@MarG66 Please test based on https://github.com/code4romania/onghub/pull/404.

**Comment by MarG66** [comment]
@radulescuandrew 
All good. No issues so far.
