### ISSUE TITLE
[Tables] Filters: Add option 'Show all' to undo a filter selection

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#357]
**Describe the bug**
After applying filters, I can't undo a filter selection to "All", unless I reset all filters.

**Steps to reproduce the behavior**
1. Login
2. Go to any table
3. Click on 'Filters'
4. Select a filter (eg. a dropdown field)
5. User can't delesect the option

**Expected behavior**
User should have the option to "deselect" a filter option individually - all filters should have a default state "show all" that user can select after they selected a value.

**Screenshots**
<img width="1438" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/d89c1ddd-fc60-4cfb-8e2e-5a231cc06c21">

**Comment by overeha** [comment]
The "All" option is not displaying in filters yet in teh SuperAdmin account for example. And I cannot deselect the selection I have made. 
<img width="1420" alt="Screenshot 2023-11-16 at 12 32 31" src="https://github.com/code4romania/onghub/assets/45068169/120bdc1b-53d3-4a96-a9a3-ede2a60cd210">

**Comment by radulescuandrew** [comment]
@overeha There are many places where this should be added if we want it all over the place. 
Mario will find all the places, @AndreeaMariaP please handle.

**Comment by MarG66** [comment]
@radulescuandrew @AndreeaMariaP 

Super-Admin: (falicity.britlee@moabuild.com)

"ONG-uri" page - https://app-staging.onghub.ro/organizations
"Vedere de ansamblu" tab, "Lista utilizatori" at the bottom, inside NGO detail page - https://app-staging.onghub.ro/organizations/1/overview
"Aplicatiile mele" tab, inside NGO detail page - https://app-staging.onghub.ro/organizations/2/applications
"Solicitari Acces" page - https://app-staging.onghub.ro/requests
"Toate aplicatiile" page - https://app-staging.onghub.ro/applications/overview
"Cereri acces aplicatii" tab - https://app-staging.onghub.ro/applications/requests
"Lista ONG-uri" tab, inside application detail page - https://app-staging.onghub.ro/application/2/installs


Admin: (brix.grayer@moabuild.com)

"Utilizatori" page - https://app-staging.onghub.ro/users/list
"Invitatii trimise" tab - https://app-staging.onghub.ro/users/invites
