### ISSUE TITLE
[Employees] Missing employee access management to apps (individually)

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#359]
**Describe the bug**

**Steps to reproduce the behavior**
1. Login as AdminONG
2. Click on Users in the sidebar menu
3. See missing info about access to apps

**Expected behavior**
AdminONG should be able to control access of each of their employees to each of the apps.
Figma: https://www.figma.com/file/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?type=design&node-id=1284-19129&mode=design&t=4rPW3BvTHkju3WTd-4

**Screenshots**
![image](https://github.com/code4romania/onghub/assets/95479576/2f7633f1-40ec-433d-b351-eb88a953afcc)

**Comment by radulescuandrew** [comment]
The fix of this issue is also related to #326. If we include the Admins in the user lists, the result must be handled different. @overeha

**Comment by radulescuandrew** [comment]
@overeha @anastk-code4 Fixed in #409. Please test.
