### ISSUE TITLE
[Registration] Uploading an incorrect file is allowed

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#361]
**Describe the bug**
When uploading the organization's statute, the user is prompted that the document (if not pdf/doc/docx) does not have the right format, but the document is uploaded.
The documents that can be uploaded are filtered to the accepted formats, but a user can go around this setting.

**Steps to reproduce the behavior**
1. Go to https://app-staging.onghub.ro/new/legal
2. Scroll down to 'Statutul organizatiei' section
3. Press 'Incarca fisier'
4. Select a document that is not pdf/doc/docx
5. Save the organization

**Expected behavior**
The document/organization is not saved, and a prompt shows what files are allowed.

**Device information**
 - OS: MacOS 13.5.2
 - Browser: Chrome 117.0.5938.92 [ARM]

**Comment by anastk-code4** [comment]
linked to https://github.com/code4romania/onghub/issues/341

**Comment by dragos1195** [comment]
@anastk-code4 @overeha @birloiflorian 

Created PR https://github.com/code4romania/onghub/pull/406
Cannot prevent trying to upload a different type of file, but the backend throws an error on this scenario.

However, I've added a confirmation modal on deletion of the organization statute.
Also, there was a visual bug when adding a wrong type of file, as it showed on frontend that it was uploaded, it was not the case and now it is fixed.
