### ISSUE TITLE
[Applications] SuperAdmin can't see NGOs that have Centru Civic app installed from app page view

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#366]
**Describe the bug**
Logged in as a SuperAdmin user, when I open an apps page I want to see a list of all NGOs that use that app. In this particular case, the app type is set as 'Website simplu', and as well as for other apps with similar settings, I can't see the list of NGOs using this app from apps page (see screenshot). 

**Steps to reproduce the behavior**
1. Login as SuperAdmin
2. Go to 'All apps' page
3. Open app page for Centru Civic
4. Click on 'Lista Ong-uri' tab to see which NGOs have this app installed
5. Can't see any NGOs in the list, even though the app is set as 'automatically added'

**Expected behavior**
Superadmin should be able to see the table with all NGO that use this app (NGOs that have this app 'added').

**Screenshots**
<img width="1418" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/44eb83d2-66f9-4781-a5f5-e4aff47ef3aa">

even though, logged in as a AdminONG user I can see this app is added for my NGO (automatically added)
<img width="1418" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/b48421af-a82a-4193-845a-37f592bc3c4a">

**Comment by birloiflorian** [comment]
All organizations which have at least one service/practice program
