### ISSUE TITLE
[CivicCenter][P4G] Can't use apps properly, as AdminONG user

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#367]
**Describe the bug**
As an AdminONG user, I want to be able to manage services/practice programs from the pannel as depincted in [Figma](https://www.figma.com/file/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?type=design&node-id=1920-34232&mode=design&t=o5qxBbWQ8Pu75wgI-4). 
At this moment, I can't use apps as AdminONG user, but can manage services/practice programs for an NGO if I login as SuperAdmin and go to that NGO's profile. 

**Steps to reproduce the behavior**
1. Go to AdminONG
2. Go to my apps
3. Go to Centru Civic / P4G app 
4. Can t see the button that leads the user to the page where they can manage their services / practice programs

**Expected behavior**
See a button 'Gestioneaza servicii' / 'Gestioneaza programe de practica' as depicted in Figma.

**Screenshots**
<img width="1418" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/f34a1f87-6681-4ba2-aba6-c03bc43e1928">

As SuperAdmin, I can manage this though:
<img width="1418" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/169d7cef-9e06-4fef-a5a8-e80428b17f5d">

**Comment by dragos1195** [comment]
@anastk-code4 @overeha @radulescuandrew 

The behavior of the P4G and CC apps was agreed upon and implemented as follows: each app needs to be set as a "simple login" type, so an Admin would need to add it manually from the "all apps" list, to prevent adding them for each existing organization by default.

Thus, I've deleted all existing apps that seemed to be CC or P4G, and created new ones with "simple login" (no login required, but this will enforce an admin to add it manually).
Now, each organization would need to "add/install" the applications. 

Furthermore, as described above, yes, the SuperAdmin can see the Practice Programs and Services tabs (while viewing an organization) and add items to it, even though the organization does not have the app installed. This was developed this way to prevent unnecessary checks.

No PR was needed.

**Comment by radulescuandrew** [comment]
@mirunaioana-msc @overeha  Please review this and advise.
