### ISSUE TITLE
[i18n] Some texts appear in the app but not in the translations

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#369]
**Describe the bug**
All the texts must be internationalized and available to be translated without modifying the code.

- [ ] [E-mail templates are not internationalized at all](https://github.com/code4romania/onghub/blob/8a3da93fc60a2af75f73922e17c437c7ba7c7600/backend/src/mail/constants/template.constants.ts#L1-L0)

Other missing texts:
- [x] https://github.com/code4romania/onghub/blob/929bff3166506424b2c12196119c2c5d09346fe6/frontend/src/pages/apps-store/components/EditApplication.tsx#L90
- [x] https://github.com/code4romania/onghub/blob/e9d8971facbdd30d3484439c87dcf36e59a077c9/frontend/src/pages/apps-store/constants/ApplicationType.enum.ts#L16-L18
- [x] https://github.com/code4romania/onghub/blob/929bff3166506424b2c12196119c2c5d09346fe6/frontend/src/pages/apps-store/components/EditApplication.tsx#L76

**Screenshots**

![image](https://github.com/code4romania/onghub/assets/2820084/97e68ffb-8e2b-49b8-a7a7-43bdf95a6dbc)
![image](https://github.com/code4romania/onghub/assets/2820084/92cca207-5c51-4c3e-9ed9-f74ff9bae589)
![image](https://github.com/code4romania/onghub/assets/2820084/119118be-843d-4b28-9f54-9a089ec0bb83)

**Comment by radulescuandrew** [comment]
@overeha Emails can't be internationalized yet, we don't have the internationalization logic in the backend, as we discussed also for the "Domains". The rest, is done.
