### ISSUE TITLE
[NGOs] Change display name on NGO list

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#370]
**Describe the bug**
SuperAdmin wants to see a list of all NGOs in ONGHub. In this list they want to see the NGO name: NGO Alias. Now, the list shows NGOs by their NGO official name. 

**Expected behavior**
Display the Alias on the column 'ONG' in this table 

**Screenshots**
<img width="1155" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/bfbdec4f-d00f-4d54-a7a4-aedd8bd06bd7">

**Comment by radulescuandrew** [comment]
Fixed in #390. Will be closed after PR closed and testing.
