### ISSUE TITLE
[Applications] Show number of NGOs and number of users in apps list

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#371]
**Describe the bug**
SuperAdmin sees a list of all the apps in ONGHub and the number of NGOs in the platform that have these apps added as well as the total number of users with access to these apps. For some apps (guessing it's the apps that are automatically added to NGOs when they receive access in ONGHub), these numbers down t show in the list, and the cell is marked by "-". 

**Steps to reproduce the behavior**
1. Login as SuperAdmin
2. Go to All apps page

**Expected behavior**
SuperAdmin can see the numbers for all apps. (even if it is repetitive or can be guessed, it s simpler like this for the user)

**Screenshots**
 <img width="1418" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/5d107506-9551-4582-ac5b-4c08f5398043">

**Comment by AnaBlidaru** [comment]
Still valid

**Comment by AnaBlidaru** [comment]
Not a bug, but a feature.
This is still the case for the apps that ”come with NGO Hub” and do not require a login: Civic Tech 911 and How to NGO.
