### ISSUE TITLE
[Applications] Change App long description validation from max. 700 chrs to unlimited

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#372]
**Describe the bug**
Character number limitation is too low. 

**Steps to reproduce the behavior**
1. Login as SuperAdmin
2. Go to 'All apps' page
3. Click on New app button
4. Fill in field 'Descriere extinsa aplicatie' 
5. See no of chars limitation

**Expected behavior**
Superadmin should be able to add more extensive description of the app, even include info like how to use the app and such.
There should be no limitation to max number of characters. If there must be one, it should be more like max 7000.

**Screenshots**
<img width="1430" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/5b25deef-af51-405a-8813-50217485c4f9">

**Comment by overeha** [comment]
Stilll happening 
<img width="1216" alt="Screenshot 2023-11-16 at 12 29 29" src="https://github.com/code4romania/onghub/assets/45068169/b9ffa534-54a9-400f-9a33-b36b2af17f0c">

**Comment by dragos1195** [comment]
@overeha please test again. The PR hasn't been merged at the moment of your test.
