### ISSUE TITLE
Make NGO name and app name clickable

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#374]
Can we make NGO's name clickable when it appears in a table, leading to NGO's profile?

<img width="1421" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/59b2e2b2-fa3a-4588-8420-e8cf6efd660e">

Also, App name leading to App's view page?

**Comment by overeha** [comment]
This issue was referring to make NGO names clickable in all tables not just in Access request. Can we please have that?

**Comment by MarG66** [comment]
@radulescuandrew I will give you all tables where there are NGO Names to be updated.

**Comment by radulescuandrew** [comment]
@MarG66 And App names

**Comment by MarG66** [comment]
These are the tables where the NGO names are displayed:

"ONG-uri" page - https://app-staging.onghub.ro/organizations
"Solicitari Acces" page - https://app-staging.onghub.ro/requests (!this has to lead to NGO registration form not NGO profile - https://app-staging.onghub.ro/requests/1/general)
"Lista ONG-uri" tab from the App detail page - https://app-staging.onghub.ro/application/6/installs

These are the tables where the App names are displayed:

Super-Admin (falicity.britlee@moabuild.com)
"Aplicatiile mele" tab from the organization detail page - https://app-staging.onghub.ro/organizations/9/applications
"Toate aplicatiile" page - https://app-staging.onghub.ro/applications/overview
"Cereri acces aplicatii" tab from "Toate aplicatiile" page - https://app-staging.onghub.ro/applications/requests

Admin (brix.grayer@moabuild.com)
Employee Edit Page - https://app-staging.onghub.ro/user/55
Add Employee Page - https://app-staging.onghub.ro/user

**Comment by radulescuandrew** [comment]
Most of the rows are now clickable.
