### ISSUE TITLE
Some modals don't display right

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#376]
**Describe the bug**
Sometimes while using ONGHUB, we came across modals looking like in the prtscr. 

**Steps to reproduce the behavior**
Not very reproduceable

**Screenshots**
![image](https://github.com/code4romania/onghub/assets/95479576/80100e48-8616-4821-93de-4c9b45a142d2)
![image](https://github.com/code4romania/onghub/assets/95479576/429acc94-abdc-4dcb-a4cb-089039f5d130)

**Comment by overeha** [comment]
tested. works ok.
