### ISSUE TITLE
[Reset password] Couldn't reset password for a particular AdminONG account

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#380]
**Describe the bug**
Forgot password for an Admin ONG account, followed the flow for resetting password but didn't receive the email to complete it. From SuperAdmin account, I can see the NGO in the list, and it has access to ONGHub.
Tested this functionality in the past with no problems, everything was working just fine. 

**Steps to reproduce the behavior**
1. Go to https://app-staging.onghub.ro/login
2. Click on 'Login' button
3. Click on 'Forgot your password?' button
4. Input email ana.stoichitoiu+test5@code4.ro
5. Redirected to screen where I should input a code received thru email
6. Didn't receive any email with a reset code

**Expected behavior**
To receive an email with a reset password code.

**Comment by radulescuandrew** [comment]
@anastk-code4 Tested with different accounts, working as expected. 
Please provide reproduction steps with a public account if the case, to be further investigated.

**Comment by AnaBlidaru** [comment]
@anastk-code4 - please check if this is still an issue or if we can close it

**Comment by mirunaioana-msc** [comment]
the issue cannot be reproduced.
