### ISSUE TITLE
Change to new version of logo

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#416]
New logo: 
![NGOHUB](https://github.com/code4romania/onghub/assets/95479576/6b989a54-9715-4844-850b-1024fa557c9b)

in topbar 
![app](https://github.com/code4romania/onghub/assets/95479576/493db2ca-d7de-40aa-b29c-f5f0bcb5f149)

**Comment by anastk-code4** [comment]
also here 
<img width="407" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/1a903aa1-e8e1-4d9b-b83d-2c5beedcd7fb">

**Comment by tudoramariei** [comment]
Resolved today
![Screenshot 2023-12-12 at 15 51 37](https://github.com/code4romania/onghub/assets/2820084/84b45772-79c1-491a-acf8-a19b7e3bb49e)
