### ISSUE TITLE
Paragraphs not well aligned, words are cut at the end of the row

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#420]
**Describe the bug**
See prtscr 

**Steps to reproduce the behavior**
1. Go to https://app.ngohub.ro/
2. Login
3. Go to My apps or All apps
4. Open an App page and see the description

**Expected behavior**
Paragraph is left aligned, if a word won't fit the line it is positioned on the next line.

**Screenshots**
<img width="1436" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/68190f86-f2b8-4e62-b26b-4db8f1640470">

**Comment by git-MA** [comment]
@anastk-code4 bug solved - we can close it
