### ISSUE TITLE
[NGO profile][Registration] In section "Federatii"/"Coalitii", the list of federatii and the list of coalitii is not populated with real values

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#429]
**Describe the bug**
Where: NGO profile > "Activitatea organizației" > Section "Federații și coaliții". Also in Registration form.

We need NGO Admin to be able to search a dropdown for Federatii and for Coalitii field, select multiple options, and if they can't find the one(s) they are looking for in the list, they should be able to add their own.

Lists are pre-populated with fictive values and not real values. 

**Expected behavior**
The list is populated with real values. 

**Screenshots**
![image](https://github.com/code4romania/onghub/assets/95479576/67a669da-acc3-488f-b76e-02e8e8cff7d7)

**Comment by anastk-code4** [comment]
@tudoramariei will provide the lists

**Comment by AnaBlidaru** [comment]
**FEDERAȚII**

- FFCR - Federația Fundațiilor Comunitare din România
- FONPC - Federația Organizațiilor Neguvernamentale pentru Copii
- FONSS - Federația Organizațiilor Neguvernamentale pentru Servicii Sociale
- FOND - Federația ONG pentru Dezvoltare
- Federația Coaliția pentru Educație
- FASMR - Federația Asociațiilor Studenților în Medicină din România
- Federația Coaliția Natura 2000 România
- FASFR - Federația Asociațiilor Studenților Farmaciști din România
- Federația Consiliul Tineretului din România
- Cognosis - Federația Asociațiilor Studenților la Psihologie și Științele Educației din România

**Comment by AnaBlidaru** [comment]
**COALIȚII**

- Coaliția pentru Drepturile Migranților și Refugiaților
- Coaliţia Organizaţiilor Pacienţilor cu Afecţiuni Cronice din România
- Coaliția Anti Discriminare
- Coaliția pentru Egalitate de Gen
- Coaliția România Sustenabilă

**Comment by AnaBlidaru** [comment]
@radulescuandrew @birloiflorian - I've updated the list of above and added the new issue here - https://github.com/code4romania/onghub/issues/444

**Comment by MarG66** [comment]
@AnaBlidaru - Both lists are now populated with requested values, this particular issue can be closed. Issue 444 will be fixed separately.
