### ISSUE TITLE
[NGO profile][Registration] Add new fields, reorganize sections

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#430]
**Context**
Working on future apps, we realized we need to separate official NGO information from communication information.

**Describe**
We need to introduce the following fields (another address section) in the NGO profile > "Date generale" (as well as in the Registration form > Date generale):
- "Adresa": text field, mandatory 
- "Judet": single select, mandatory
- "Oras": single select, mandatory

Also we need to visually reorganize the sections in the NGO profile > "Date generale" (as well as in the Registration form > Date generale), as described in figma: https://www.figma.com/file/cfixQXmZ7FdFatiDCpUhyK/ONG-HUB?type=design&node-id=7858-12852&mode=design&t=zIuYSwi9EOwQ3221-4

**Comment by birloiflorian** [comment]
Here we have the following changes:
1. Updated layout for create and update forms according to the figma layout
2. The new address fields were added. Here the following behaviours needs to be validated
   1. If both the address groups have the same values the checkbox for 'same address' automatically become checked
   2. If one of the addresses changes (either address, city, county) the checkbox will become unchecked
   3. Only the first address group (headquarters -> 'sediu social') is mandatory, the other one is optional
3. Updated the readonly form to support link redirects for social and fundraising sections
4. Updated the social section to only show website and facebook values all the time, while the others only if they were completed
5. Even if not present in this figma layout we still have the 'Contact Person' section as this will require more changes to remove. TBD
6. Updated some translations and wording.

**Comment by MarG66** [comment]
@birloiflorian @anastk-code4 @AnaBlidaru  there are still some issues with the location dropdown fields at point 2. The "city" field does not update according to "county" field and the data is not saved when completing the registration form. Also on the registration form the 2.i. does not happen, but only there.
With the other points I found no issues so far.
