### ISSUE TITLE
[Apps] Hide "deschide" button in app cards

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#431]
**Describe**
We need to hide the "deschide" button on the app cards in NGOHUB (until we fix some flows), in All apps and My apps page.

<img width="801" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/602ee048-a8b8-47a2-93b7-8476e864d67f">

**Comment by MarG66** [comment]
No issues found, task completed according to issue #431.
