### ISSUE TITLE
Add "info" item in the menu

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#432]
**Describe**
We need item "informatii" in the menu for all user types.
At click, it should open a new tab with link https://www.ngohub.ro/ro/informatii-generale 

<img width="180" alt="image" src="https://github.com/code4romania/onghub/assets/95479576/0f7fdcc0-ece7-4f5b-a105-1b5be0f055bd">

**Comment by MarG66** [comment]
No issues found so far, button works accordingly.
