### ISSUE TITLE
[Applications] Sort the applications alphabetically for NGOs

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#454]
**Is your feature request related to a problem? Please describe.**
It would be much easier for the NGO and the admins to see the applications sorted alphabetically. 

The feature should appear for all the apps available to the NGO (`/all-apps`) and the NGO's available applications (`/my-apps`).

**Additional context**
Apps are alphabetically ordered for the admins' `/applications/overview` page.

**Comment by mirunaioana-msc** [comment]
closed because we will sort them alphabetically and based on their status. New issue to be added
