### ISSUE TITLE
[Responsiveness] Some text can only fill half a page in some page sizes

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#456]
**Describe the bug**
When the web page has a size that hides the side menu into a hamburger menu, the text on the NGO data page fills the whole page. 
When the side menu is _inlined_ (expanded or collapsed), the text can only fill half a page, leaving a lot of empty space.

**Steps to reproduce the behavior**
1. Log in as a super admin
2. Go to `/organizations/<org_id>/general`
3. Resize the page so as to see the menu as a hamburger menu in the top-left corner
4. The text makes use of the whole screen width
5. Resize the page so as to see the menu expanded on the side
6. The text only fills 50% of the available space, leaving a lot of blank space

**Expected behavior**
The text should always make use of the whole screen width. It should behave like in `step 4`.

**Screenshots**
Expanded behavior:
![Screenshot 2024-01-22 at 10 21 08](https://github.com/code4romania/onghub/assets/2820084/e5912c6d-db1f-43a5-9ec5-976275b02df2)
Wanted behavior:
![Screenshot 2024-01-22 at 10 21 26](https://github.com/code4romania/onghub/assets/2820084/9ef9329d-6461-43af-a716-6f165a923d7d)

**Comment by dehelean-catalin** [comment]
I will fix this issue
