### ISSUE TITLE
[Registration] Orgs should be able to add a 700-2000 chars description

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#463]
**Describe the bug**
When registering an NGO, there is an issue with the length of the detailed description.
The limit should be between 500 & 2000 characters, but it is set to 500-700.

**Steps to reproduce the behavior**
1. Go to the registration page, get past the first two steps
2. At Step 3, go to: `Date de prezentare > Prezentare detaliată a organizației`
3. Add a 700-character text
4. The text is valid
5. Add one more character
6. The text is too long

**Expected behavior**
The text box should allow up to 2000 characters.

**Screenshots**
The text, 699 characters
![Screenshot 2024-02-01 at 10 35 55](https://github.com/code4romania/onghub/assets/2820084/96bf940b-f24e-4f5d-b5f2-ea11c9ddf0a5)

The invalid text (701 characters, added ` 1` to the previous text)
![Screenshot 2024-02-01 at 10 36 05](https://github.com/code4romania/onghub/assets/2820084/91f56c23-6882-4fca-a3bd-22789fe5f4c5)

The stats for the sample text used
![Screenshot 2024-02-01 at 10 35 06](https://github.com/code4romania/onghub/assets/2820084/9c354f2e-fe46-40c4-98db-d1e61f9ee014)

**Comment by radulescuandrew** [comment]
@birloiflorian Isn't this fixed already?
