### ISSUE TITLE
Update phone number format validation across NGO HUB

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/onghub#468]
Currently, phone number fields allow only romanian phone number format. 
We need to allow international phone number format.

See affected fields in [Data Dictionary NGOHUB ](https://docs.google.com/spreadsheets/d/1fz2gAj8obkblIAeKDH5tkiAfuv-gnH4Us5gywBemm2c/edit?usp=sharing)
NGOADMIN_PHONE
NGO_PHONE
NGO_REPPHONE
NGO_COUNCIL_PHONE
NGO_PPL_PHONE

**Comment by MarG66** [comment]
@dragos1195 Testing failed, feature missing from:
"Reprezentantul legal al organizației" - **Informatii legale**
"Consiliul Director al organizației" - **Informatii legale**
"Persoana de contact în relația cu NGO Hub" - **Date generale**
