### ISSUE TITLE
[Admin] Allow super-admins to download the list of NGOs

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/onghub#474]
**Is your feature request related to a problem? Please describe.**

Sometimes, admins need to get the list of NGOs to have the data set in bulk.

**Describe the solution you'd like**

Add a `Download` button on the `/organizations` page from the admin interface.

Ideally, the admin could have a selector to choose which fields to download from the NGO's data.
The alternatives section provides a more simple resolution for this.

**Describe alternatives you've considered**

Since selecting what data we want to download would involve plenty of new extra features, the data should at least have most of the data from `General data` but especially the contact details of the contact person and the NGO (name, website, city).

**Comment by mirunaioana-msc** [comment]
**Expected behaviour**:
> Add a Download button on the /organizations page from the admin interface.

Automatic download of a .csv/.xls file with all the info in general data section with the following info: 
- Date oficiale
- Informatii de contact
- Persoana de contact

**Comment by MarG66** [comment]
@mirunaioana-msc Testing passed. Currently all NGO data is downloaded not just **General Data**. Should we keep it like this?
