### ISSUE TITLE
[My organization profile] We should not have tabs on 2 rows

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/onghub#481]
**Describe the bug**

Currently if you have a smaller screen, the tabs move in 2 rows.

<img width="1409" alt="Screenshot 2024-05-17 at 2 16 51 PM" src="https://github.com/code4romania/onghub/assets/111346300/eb7979fd-078a-401b-953a-b7aba3b33188">

**Expected behavior**
Instead of displaying two rows of tabs, enable earlier the dropdown which replaces it.

**Comment by luciatugui** [comment]
We now display the select component until the screen reaches 1536px, and after that the tabs will be visible spread out. This is available for testing in the staging environment if you wish to take a look.

Another thing that could fix this issue if we think that the 1536px screen size is a bit too large, lowering the font size for the tabs (which is currently 20px) could also allow more tabs to fit in one row. 
One more option would be to remove those tabs from that place altogether and maybe move them inside the left menu, as sub options.

**Comment by MarG66** [comment]
> We now display the select component until the screen reaches 1536px, and after that the tabs will be visible spread out. This is available for testing in the staging environment if you wish to take a look.
> 
> Another thing that could fix this issue if we think that the 1536px screen size is a bit too large, lowering the font size for the tabs (which is currently 20px) could also allow more tabs to fit in one row. One more option would be to remove those tabs from that place altogether and maybe move them inside the left menu, as sub options.

Testing passed with current fix, no issues found. @mirunaioana-msc please advise, do we keep it as it is now?

**Comment by MarG66** [comment]
I will close the issue, if other changes are needed we can reopen this or make create another one
