### ISSUE TITLE
[Notification] The SuperAdmin needs to receive a notification when a new app request is submitted

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/onghub#485]
### **Context**

Currently, in NGO Hub there are a few apps which need input from the SuperAdmin in order to be used by NGOs. The SuperAdmin is not currently notified when a new app request was submitted

### **Solution**

Implement email notifications for app requests according to the [Notification matrix](https://docs.google.com/spreadsheets/d/1v9SDNb_LJ4fGtaHYFLoJ3kRaFvxHfpL7cXRBX7za8UU/edit?usp=drive_link)

**Comment by radulescuandrew** [comment]
Done, deployed in staging v1.0.18. 

@andrei-manda please test.
