### ISSUE TITLE
[Email notification] Change text for email notification for approving a registration request

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/onghub#494]
New text:

SUBJECT:
Bun venit în NGO Hub!
TITLE:
Activează-ți contul
TEXT:
Bună,
Contul de NGO Hub al organizației tale a fost creat cu succes. Ți-am pregătit o parolă temporară cu care îți poți activa contul pentru a-ți crea apoi parola ta unică.
Username:
Parolă temporară:
Parola temporară este generată automat, și conține caractere diverse. Ai grijă când o copiezi, să nu adaugi un spațiu în plus sau să selectezi un caracter în minus.
BUTON: Accesează NGO Hub
Sau accesează link-ul următor: [app.ngohub.ro](http://app.ngohub.ro/)
După ce îți setezi parola ta unică, vei putea accesa toate soluțiile digitale disponibile în NGO Hub, folosind același cont unic.
Dacă întâmpini vreo problemă, ne poți scrie pe adresa [civic@code4.ro](mailto:civic@code4.ro)
Cu drag,
Echipa Code for Romania

**Comment by radulescuandrew** [comment]
@tudoramariei Asta e fixat in commitul tau de aici. Please close. 

https://github.com/code4romania/terraform-ngohub/commit/de8e3303cec2ff9082b25b383291735ad288d5e1

**Comment by tudoramariei** [comment]
Thanks for the heads-up!
