### ISSUE TITLE
Revise 'Informatii de contact' Section

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/onghub#504]
**ISSUES**:
- the checkbox seems to be enabled when the user is NOT in edit mode
- the system must displays "-" when the City and County inputs are empty 

![xrayScreenShot_2024-07-01_16-55-48-275](https://github.com/code4romania/onghub/assets/49789938/d6093a03-dfda-47b9-82f1-7b7a9dc287d2)

**Comment by luciatugui** [comment]
Now, we no longer display the checkbox in read-only mode.
