### ISSUE TITLE
 Save Button Doesn't Work on 'Informatii Legale' Tab

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/onghub#505]
**Steps of Reproduction:**
1. Access the 'Informatii Legale' tab (as Super-Admin/Admin)
2. Click on "Editeaza" button
3. Update some data
4. Click on "Salveaza modificari" button

**Expected Result**:
4. The updated data are saved

**Actual Result**:
4. The button doesn't work - is clickable but no action is initiated

![xrayScreenShot_2024-07-01_17-00-36-898](https://github.com/code4romania/onghub/assets/49789938/5f5c1b0c-4d39-432a-ae99-a02e51a4dde6)

**Comment by MarG66** [comment]
@radulescuandrew @andrei-manda Issue related to organisation statute doc.

If we re-upload the organisation statute the user will be able to save the data on the respective tab.
