### ISSUE TITLE
Missing Dashboard Elements

### ISSUE THREAD

**Issue by MarG66** [code4romania/onghub#532]
There are missing elements from the dashboard page on the Super-Admin view.
- Missing progress report based on last month - displayed inside the statistics cards
- Incomplete labels for table entries
- Missing "Cereri in asteptare" graph line

See SS (Red arrows display missing elements)
![SA_Dash](https://github.com/code4romania/onghub/assets/118546170/4b2bcd94-3dc6-4181-86ed-aadc6eb43a2b)

Also on Admin/Employee dashboard missing progress report based on last month.

See SS (Red arrows display missing elements from current app)
![lastMonthMissing](https://github.com/code4romania/onghub/assets/118546170/3ef5b75d-17fe-4d48-a64d-3bd44647bb17)

**Comment by radulescuandrew** [comment]
Wont do, was removed from scope last year.
