### ISSUE TITLE
Legal Representative Email Returns Validity Error When Entered Without Phone Number

### ISSUE THREAD

**Issue by MarG66** [code4romania/onghub#578]
**Preconditions:**
The user must be on the **Step 5** of the NGO registration form.

**Steps to Reproduce:**
1. Enter an valid email address in the "E-mail" input
2. Copy paste an valid email address in the "E-mail" input
3. Enter a valid phone number in the "Telefon" input
4. Enter an valid email address in the "E-mail" input
5. Copy paste an valid email address in the "E-mail" input

**Expected Results:**
1,2,4,5. No validation errors are returned by the "E-mail" input.

**Actual Results:**
1,2. The "E-mail-ul are un format invalid." error is returned even if the email is valid.
4,5. No error is returned by the "E-mail" input.

**Comment by andrei-manda** [comment]
bug fixed
