### ISSUE TITLE
Incorrect Settlements Displayed for NGO Correspondence Address 

### ISSUE THREAD

**Issue by MarG66** [code4romania/onghub#584]
**Preconditions:**
The user must be logged in on the Step 3 of NGO registration form.

**Steps to Reproduce:**
1. Go to "Judet" and "Localitate" inputs from "Date oficiale" section
2. Select a county and a settlement
3. Go to "Judet" and "Localitate" inputs from "Informatii de contact" section
4. Open the "Localitate" dropdown menu

**Expected Results:**
4. No action is take because no county is selected for the "Judet" input.

**Actual Results:**
4. A dropdown is displayed containing the settlements from the county selected in step 2.

**Note:**
The  "Localitate" inputs from "Informatii de contact" section displays the save values from "Localitate" inputs from "Date oficiale" section,
no matter what counti is selected.

**Comment by radulescuandrew** [comment]
Resolved in another issue.
