### ISSUE TITLE
UI adjustments and functionality changes

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/onghub#609]
The new feature will impact the following sections of the application, necessitating adjustments:

## NGOs List (Super-Admin account:  _/organizations_)

- the 'Status actualizare' column in the table needs to be divided into two separate columns.
- the download table functionality must be updated to reflect this change.
- the filters will also need to be revised; currently we have a filter for 'Status actualizare date'
- the sorting functionality must be updated to allow sorting based on each of these new columns individually.

**Questions**:
1. What should the 'Ultima actualizare date' column refer to: the most recent update in the Financial tab or the Open Data tab?
2. If we split the 'Status actualizare' column, should there be filters for both of the new columns?

**Comment by radulescuandrew** [comment]
@andrei-manda We didn't split anything anymore. Will close it as invalid.
